services:
  spring-prod:
    image: mdzenos/spring_core:1.0
    container_name: spring-prod
    ports:
      - '${PROD_PORT:-8000}:8000'
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT_CONTAINER:-5432}
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-yourpassword}
    networks:
      - shared_network_144
    profiles:
      - prod

  spring-dev:
    image: mdzenos/spring_core:1.0
    container_name: spring-dev
    entrypoint: ''
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./.m2:/root/.m2
      - ./dev.sh:/app/dev.sh
    ports:
      - '${DEV_PORT:-8001}:8000'
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT_CONTAINER:-5432}
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-yourpassword}
    command: bash dev.sh
    networks:
      - shared_network_144
    profiles:
      - dev

  sping-postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - '${DB_PORT_HOST:-5439}:${DB_PORT_CONTAINER:-5432}'
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-yourpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network_144
    profiles:
      - dev
      - prod

networks:
  shared_network_144:
    external: true
volumes:
  postgres_data:

# docker compose --profile dev down && docker compose --profile dev up -d
# docker logs -f sping-dev
# docker rm -f sping-dev
